# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
